#version 450

layout( local_size_x = 64 ) in;

const uint BUFFER_SIZE = 500;  // must match numElements in main.cpp


layout( set = 0, binding = 0 ) readonly buffer inputBufferLayout
{
    int inputBuffer[];
};

layout( set = 0, binding = 1 ) writeonly buffer outputBufferLayout
{
    float outputBuffer[];
};


void main()
{
    uint processingIndex = gl_GlobalInvocationID.x;
    if ( processingIndex >= BUFFER_SIZE )
        return;

    outputBuffer[ processingIndex ] = inputBuffer[ processingIndex ] * 4.2f;
}
